apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: annual-lime-urial
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: annual-lime-urial 
  name: annual-lime-urial
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: annual-lime-urial 
